### ISSUE TITLE
яндере дев

### ISSUE THREAD

**Issue by erxson** [UnFamousSoul/Reviews-Bot#1]
ЪХПАХЪЗПЭЫВПАХЩЗСГВЗСФЫШЩВГСЗЩФЫГВЗСЩФЫЩШВЗФЫВ

**Comment by UnFamousSoul** [comment]
Да, я, вопросы?

**Comment by erxson** [comment]
Неактуал. Ты тогда в войсе сказал "эрик сейчас иссуе создаст с яндере дев" или че-то такое было
